export function buildReportHTML(data) {
    const { files, results, generatedAt, settings } = data;
    const date = new Date(generatedAt).toLocaleString();
    const fileNames = Object.keys(files || {});

    const overallScore = computeOverallScore(results);
    const scoreColor = overallScore >= 80 ? '#4caf82' : overallScore >= 50 ? '#e0a84e' : '#e05c5c';

    const fileSections = fileNames.map(name => buildFileSection(name, files[name], results[name] || {})).join('');

    return `<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DevLens Report — ${date}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f1117;color:#c9d1d9;line-height:1.6;padding:2rem}
h1,h2,h3{font-weight:600;color:#e6edf3}
h1{font-size:1.6rem;margin-bottom:.25rem}
h2{font-size:1.2rem;margin:2rem 0 .75rem;border-bottom:1px solid #30363d;padding-bottom:.4rem}
h3{font-size:1rem;margin:1rem 0 .5rem;color:#8b949e}
.header{display:flex;align-items:center;justify-content:space-between;margin-bottom:2rem;padding-bottom:1.5rem;border-bottom:1px solid #30363d}
.score-badge{width:72px;height:72px;border-radius:50%;border:4px solid ${scoreColor};display:flex;flex-direction:column;align-items:center;justify-content:center;flex-shrink:0}
.score-num{font-size:1.5rem;font-weight:700;color:${scoreColor};line-height:1}
.score-sub{font-size:.65rem;color:#8b949e}
.meta{color:#8b949e;font-size:.85rem;margin-top:.25rem}
.summary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:1rem;margin-bottom:2rem}
.stat-card{background:#161b22;border:1px solid #30363d;border-radius:8px;padding:1rem;text-align:center}
.stat-num{font-size:1.8rem;font-weight:700;color:#e6edf3}
.stat-label{font-size:.75rem;color:#8b949e;margin-top:.2rem}
.file-section{background:#161b22;border:1px solid #30363d;border-radius:8px;margin-bottom:1.5rem;overflow:hidden}
.file-header{background:#1c2128;padding:.75rem 1rem;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #30363d}
.file-name{font-family:monospace;font-size:.9rem;color:#58a6ff}
.file-meta{font-size:.75rem;color:#8b949e}
.file-body{padding:1rem}
.finding{border-left:3px solid #30363d;padding:.5rem .75rem;margin-bottom:.5rem;background:#0d1117;border-radius:0 4px 4px 0;font-size:.85rem}
.finding.error{border-color:#e05c5c}
.finding.warning{border-color:#e0a84e}
.finding.info{border-color:#5c9ee0}
.finding-top{display:flex;align-items:center;gap:.5rem;margin-bottom:.2rem}
.badge{font-size:.7rem;padding:.1rem .4rem;border-radius:3px;font-weight:600;text-transform:uppercase}
.badge-error{background:#3d1a1a;color:#e05c5c}
.badge-warning{background:#3d2e1a;color:#e0a84e}
.badge-info{background:#1a2a3d;color:#5c9ee0}
.badge-high{background:#3d1a1a;color:#e05c5c}
.badge-medium{background:#3d2e1a;color:#e0a84e}
.badge-low{background:#1a2e1a;color:#4caf82}
.finding-rule{font-family:monospace;font-size:.75rem;color:#8b949e}
.finding-loc{margin-left:auto;font-size:.75rem;color:#8b949e;font-family:monospace}
.finding-msg{color:#c9d1d9}
.finding-snippet{background:#0a0d12;padding:.3rem .5rem;border-radius:4px;font-family:monospace;font-size:.78rem;color:#8b949e;margin-top:.3rem;overflow-x:auto;white-space:pre}
.wcag-table{width:100%;border-collapse:collapse;font-size:.85rem;margin-top:.5rem}
.wcag-table th{text-align:left;padding:.4rem .6rem;border-bottom:1px solid #30363d;color:#8b949e;font-weight:500}
.wcag-table td{padding:.4rem .6rem;border-bottom:1px solid #21262d;vertical-align:top}
.pass{color:#4caf82}
.fail{color:#e05c5c}
.empty{color:#8b949e;font-style:italic;font-size:.85rem;padding:.5rem 0}
.dep-list{list-style:none;font-family:monospace;font-size:.83rem}
.dep-list li{padding:.2rem 0;color:#8b949e}
.dep-list li::before{content:'→ ';color:#5c9ee0}
.cycle-warning{background:#2d1a1a;border:1px solid #5a2020;border-radius:6px;padding:.75rem;margin-bottom:1rem;font-size:.85rem;color:#e05c5c}
.footer{margin-top:3rem;padding-top:1rem;border-top:1px solid #30363d;font-size:.78rem;color:#8b949e;text-align:center}
</style>
</head>
<body>
<div class="header">
    <div>
        <h1>DevLens Analysis Report</h1>
        <div class="meta">Generated ${date} &nbsp;|&nbsp; ${fileNames.length} file${fileNames.length !== 1 ? 's' : ''} analyzed</div>
    </div>
    <div class="score-badge">
        <span class="score-num">${overallScore}</span>
        <span class="score-sub">/ 100</span>
    </div>
</div>

${buildSummaryGrid(files, results)}

${fileSections}

<div class="footer">Generated by DevLens &mdash; Offline JavaScript Analysis Tool</div>
</body>
</html>`;
}

function computeOverallScore(results) {
    if (!results) return 0;
    const scores = [];
    for (const fileResult of Object.values(results)) {
        const analysis = fileResult.analysis || [];
        const errors = analysis.filter(f => f.severity === 'error').length;
        const warnings = analysis.filter(f => f.severity === 'warning').length;
        const penalty = errors * 8 + warnings * 3;
        scores.push(Math.max(0, 100 - penalty));

        const a11y = fileResult.accessibility || [];
        const a11yFails = a11y.filter(f => !f.pass).length;
        if (a11yFails > 0) scores.push(Math.max(0, 100 - a11yFails * 10));
    }
    if (!scores.length) return 100;
    return Math.round(scores.reduce((a, b) => a + b, 0) / scores.length);
}

function buildSummaryGrid(files, results) {
    let totalErrors = 0, totalWarnings = 0, totalInfos = 0, totalLeaks = 0;
    for (const r of Object.values(results || {})) {
        for (const f of (r.analysis || [])) {
            if (f.severity === 'error') totalErrors++;
            else if (f.severity === 'warning') totalWarnings++;
            else totalInfos++;
        }
        totalLeaks += (r.memory || []).length;
    }
    const totalLines = Object.values(files || {}).reduce((s, f) => s + (f.content || '').split('\n').length, 0);

    return `
<div class="summary-grid">
    <div class="stat-card"><div class="stat-num">${Object.keys(files || {}).length}</div><div class="stat-label">Files Analyzed</div></div>
    <div class="stat-card"><div class="stat-num">${totalLines.toLocaleString()}</div><div class="stat-label">Lines of Code</div></div>
    <div class="stat-card"><div class="stat-num" style="color:#e05c5c">${totalErrors}</div><div class="stat-label">Errors</div></div>
    <div class="stat-card"><div class="stat-num" style="color:#e0a84e">${totalWarnings}</div><div class="stat-label">Warnings</div></div>
    <div class="stat-card"><div class="stat-num" style="color:#5c9ee0">${totalInfos}</div><div class="stat-label">Info</div></div>
    <div class="stat-card"><div class="stat-num" style="color:#e0a84e">${totalLeaks}</div><div class="stat-label">Leak Patterns</div></div>
</div>`;
}

function buildFileSection(name, file, result) {
    const lines = (file.content || '').split('\n').length;
    const analysis = result.analysis || [];
    const a11y = result.accessibility || [];
    const memory = result.memory || [];
    const dep = result.dependency || null;

    return `
<div class="file-section">
    <div class="file-header">
        <span class="file-name">${esc(name)}</span>
        <span class="file-meta">${lines} lines &nbsp;|&nbsp; ${file.type || 'unknown'}</span>
    </div>
    <div class="file-body">
        ${buildAnalysisSection(analysis)}
        ${a11y.length ? buildA11ySection(a11y) : ''}
        ${memory.length ? buildMemorySection(memory) : ''}
    </div>
</div>`;
}

function buildAnalysisSection(findings) {
    if (!findings.length) return '<p class="empty">No static analysis findings.</p>';
    const sorted = [...findings].sort((a, b) => {
        const order = { error: 0, warning: 1, info: 2 };
        return (order[a.severity] ?? 3) - (order[b.severity] ?? 3);
    });
    return `<h3>Static Analysis (${findings.length} finding${findings.length !== 1 ? 's' : ''})</h3>
${sorted.map(f => `
<div class="finding ${f.severity || 'info'}">
    <div class="finding-top">
        <span class="badge badge-${f.severity || 'info'}">${f.severity || 'info'}</span>
        <span class="finding-rule">${esc(f.ruleId || '')}</span>
        ${f.line ? `<span class="finding-loc">Line ${f.line}</span>` : ''}
    </div>
    <div class="finding-msg">${esc(f.message || '')}</div>
    ${f.snippet ? `<pre class="finding-snippet">${esc(f.snippet)}</pre>` : ''}
</div>`).join('')}`;
}

function buildA11ySection(findings) {
    const fails = findings.filter(f => !f.pass);
    if (!fails.length) return '<h3>Accessibility</h3><p class="empty pass">All checks passed.</p>';
    return `<h3>Accessibility (${fails.length} failure${fails.length !== 1 ? 's' : ''})</h3>
<table class="wcag-table">
    <thead><tr><th>Criterion</th><th>Rule</th><th>Message</th></tr></thead>
    <tbody>
    ${fails.map(f => `<tr>
        <td>${esc(f.criterion || '')}</td>
        <td><span class="badge badge-error">${esc(f.id || '')}</span></td>
        <td>${esc(f.message || '')}</td>
    </tr>`).join('')}
    </tbody>
</table>`;
}

function buildMemorySection(findings) {
    if (!findings.length) return '';
    return `<h3>Memory Leak Patterns (${findings.length})</h3>
${findings.map(f => `
<div class="finding ${f.severity || 'warning'}">
    <div class="finding-top">
        <span class="badge badge-${f.severity || 'medium'}">${f.severity || 'medium'}</span>
        <span class="finding-rule">${esc(f.type || '')}</span>
        ${f.line ? `<span class="finding-loc">Line ${f.line}</span>` : ''}
    </div>
    <div class="finding-msg">${esc(f.description || '')}</div>
    ${f.snippet ? `<pre class="finding-snippet">${esc(f.snippet)}</pre>` : ''}
</div>`).join('')}`;
}

function esc(str) {
    return String(str || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;');
}