const emojiMap = {
  smile: '😄', grin: '😁', joy: '😂', rofl: '🤣', smiley: '😃',
  laughing: '😆', wink: '😉', blush: '😊', heart_eyes: '😍',
  kissing_heart: '😘', thinking: '🤔', raised_eyebrow: '🤨',
  neutral_face: '😐', expressionless: '😑', no_mouth: '😶',
  smirk: '😏', unamused: '😒', roll_eyes: '🙄', grimacing: '😬',
  lying_face: '🤥', relieved: '😌', pensive: '😔', sleepy: '😪',
  drooling_face: '🤤', sleeping: '😴', mask: '😷', face_with_thermometer: '🤒',
  sneezing_face: '🤧', hot_face: '🥵', cold_face: '🥶', woozy_face: '🥴',
  exploding_head: '🤯', cowboy_hat_face: '🤠', partying_face: '🥳',
  sunglasses: '😎', nerd_face: '🤓', monocle_face: '🧐',
  confused: '😕', worried: '😟', slightly_frowning_face: '🙁',
  frowning_face: '☹️', open_mouth: '😮', hushed: '😯',
  astonished: '😲', flushed: '😳', pleading_face: '🥺',
  anguished: '😧', fearful: '😨', cold_sweat: '😰', disappointed_relieved: '😥',
  cry: '😢', sob: '😭', scream: '😱', confounded: '😖',
  persevere: '😣', disappointed: '😞', sweat: '😓', weary: '😩',
  tired_face: '😫', yawning_face: '🥱', triumph: '😤', rage: '😡',
  angry: '😠', skull: '💀', poop: '💩', clown_face: '🤡',
  japanese_ogre: '👹', japanese_goblin: '👺', ghost: '👻',
  alien: '👽', space_invader: '👾', robot: '🤖',
  thumbsup: '👍', '+1': '👍', thumbsdown: '👎', '-1': '👎',
  clap: '👏', raised_hands: '🙌', open_hands: '👐', pray: '🙏',
  handshake: '🤝', point_up: '☝️', point_down: '👇',
  point_left: '👈', point_right: '👉', fu: '🖕', wave: '👋',
  ok_hand: '👌', v: '✌️', crossed_fingers: '🤞', metal: '🤘',
  call_me_hand: '🤙', muscle: '💪', writing_hand: '✍️', selfie: '🤳',
  heart: '❤️', orange_heart: '🧡', yellow_heart: '💛',
  green_heart: '💚', blue_heart: '💙', purple_heart: '💜',
  black_heart: '🖤', broken_heart: '💔', heavy_heart_exclamation: '❣️',
  two_hearts: '💕', revolving_hearts: '💞', heartbeat: '💓',
  heartpulse: '💗', sparkling_heart: '💖', cupid: '💘',
  gift_heart: '💝', heart_decoration: '💟', peace_symbol: '☮️',
  star: '⭐', star2: '🌟', dizzy: '💫', boom: '💥', sparkles: '✨',
  fire: '🔥', tada: '🎉', confetti_ball: '🎊', balloon: '🎈',
  trophy: '🏆', medal_sports: '🏅', first_place_medal: '🥇',
  check: '✅', white_check_mark: '✅', x: '❌', warning: '⚠️',
  no_entry: '⛔', stop_sign: '🛑', sos: '🆘', information_source: 'ℹ️',
  question: '❓', exclamation: '❗', grey_question: '❔',
  100: '💯', zero: '0️⃣', one: '1️⃣', two: '2️⃣',
  bulb: '💡', wrench: '🔧', hammer: '🔨', gear: '⚙️',
  lock: '🔒', unlock: '🔓', key: '🔑', mag: '🔍',
  link: '🔗', paperclip: '📎', scissors: '✂️', memo: '📝',
  pencil: '✏️', pen: '🖊️', notebook: '📓', books: '📚',
  book: '📖', label: '🏷️', bookmark: '🔖', money_bag: '💰',
  email: '📧', inbox_tray: '📥', outbox_tray: '📤',
  mailbox: '📫', package: '📦', calendar: '📅', date: '📅',
  phone: '📱', computer: '💻', keyboard: '⌨️', mouse: '🖱️',
  printer: '🖨️', floppy_disk: '💾', cd: '💿', dvd: '📀',
  camera: '📷', video_camera: '📹', tv: '📺', radio: '📻',
  telephone_receiver: '📞', pager: '📟', fax: '📠',
  battery: '🔋', electric_plug: '🔌', bulb2: '💡', flashlight: '🔦',
  rocket: '🚀', satellite: '🛰️', airplane: '✈️', car: '🚗',
  bus: '🚌', train: '🚆', ship: '🚢', anchor: '⚓',
  house: '🏠', office: '🏢', hospital: '🏥', school: '🏫',
  earth_africa: '🌍', earth_americas: '🌎', earth_asia: '🌏',
  world_map: '🗺️', globe_with_meridians: '🌐', compass: '🧭',
  cat: '🐱', dog: '🐶', mouse2: '🐭', hamster: '🐹',
  rabbit: '🐰', fox_face: '🦊', bear: '🐻', panda_face: '🐼',
  koala: '🐨', tiger: '🐯', lion: '🦁', cow: '🐮',
  pig: '🐷', frog: '🐸', monkey: '🐵', chicken: '🐔',
  penguin: '🐧', bird: '🐦', hatching_chick: '🐣', duck: '🦆',
  eagle: '🦅', owl: '🦉', bat: '🦇', wolf: '🐺', boar: '🐗',
  horse: '🐴', unicorn: '🦄', bee: '🐝', bug: '🐛',
  butterfly: '🦋', snail: '🐌', shell: '🐚', beetle: '🪲',
  ant: '🐜', mosquito: '🦟', cricket: '🦗', spider: '🕷️',
  turtle: '🐢', snake: '🐍', lizard: '🦎', dragon_face: '🐲',
  sauropod: '🦕', t_rex: '🦖', whale: '🐋', dolphin: '🐬',
  fish: '🐟', tropical_fish: '🐠', blowfish: '🐡', shark: '🦈',
  octopus: '🐙', sneezing: '🤧', apple: '🍎', green_apple: '🍏',
  pear: '🍐', tangerine: '🍊', lemon: '🍋', banana: '🍌',
  watermelon: '🍉', grapes: '🍇', strawberry: '🍓', melon: '🍈',
  cherries: '🍒', peach: '🍑', mango: '🥭', pineapple: '🍍',
  pizza: '🍕', hamburger: '🍔', fries: '🍟', hotdog: '🌭',
  sandwich: '🥪', taco: '🌮', burrito: '🌯', sushi: '🍣',
  ramen: '🍜', spaghetti: '🍝', rice: '🍚', curry: '🍛',
  coffee: '☕', tea: '🍵', beer: '🍺', wine_glass: '🍷',
  cocktail: '🍸', champagne: '🍾', cake: '🎂', birthday: '🎂',
  cookie: '🍪', chocolate_bar: '🍫', candy: '🍬', lollipop: '🍭',
  soccer: '⚽', basketball: '🏀', football: '🏈', baseball: '⚾',
  tennis: '🎾', volleyball: '🏐', rugby_football: '🏉', golf: '⛳',
  bow_and_arrow: '🏹', fishing_pole_and_fish: '🎣', boxing_glove: '🥊',
  dart: '🎯', video_game: '🎮', joystick: '🕹️', game_die: '🎲',
  chess_pawn: '♟️', jigsaw: '🧩', musical_note: '🎵', notes: '🎶',
  microphone: '🎤', headphones: '🎧', guitar: '🎸', piano: '🎹',
  violin: '🎻', trumpet: '🎺', drums: '🥁', saxophone: '🎷',
  art: '🎨', frame_with_picture: '🖼️', paintbrush: '🖌️',
  rainbow: '🌈', sunny: '☀️', cloud: '☁️', partly_sunny: '⛅',
  rain: '🌧️', snow: '❄️', snowflake: '❄️', zap: '⚡',
  tornado: '🌪️', fog: '🌫️', wind_face: '🌬️', umbrella: '☂️',
  droplet: '💧', ocean: '🌊', seedling: '🌱', tree: '🌳',
  palm_tree: '🌴', cactus: '🌵', tulip: '🌷', rose: '🌹',
  sunflower: '🌻', blossom: '🌼', hibiscus: '🌺', mushroom: '🍄',
  four_leaf_clover: '🍀', fallen_leaf: '🍂', leaves: '🍃',
  construction: '🚧', no_entry_sign: '🚫', name_badge: '📛',
  symbols: '🔣', abc: '🔤', abcd: '🔡', capital_abcd: '🔠',
  soon: '🔜', end: '🔚', on: '🔛', top: '🔝', back: '🔙',
};

export { emojiMap };